# Generated by Django 5.1.3 on 2024-12-03 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("addresses", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="address",
            options={"verbose_name": "Endereço", "verbose_name_plural": "Endereços"},
        ),
        migrations.AlterModelOptions(
            name="city",
            options={"verbose_name": "Cidade", "verbose_name_plural": "Cidades"},
        ),
        migrations.AlterField(
            model_name="address",
            name="city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="addresses.city"
            ),
        ),
    ]
