version: "3.9"
services:
  db:
    image: postgres:15
    env_file:
      - ./envs/postgres.env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "jeffersson", "-d", "systemsales"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    networks:
      - mynetwork

  web_api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./django:/api
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./envs/postgres.env
    networks:
      - mynetwork

volumes:
  postgres_data:

networks:
  mynetwork:

