# Generated by Django 5.1.3 on 2024-12-03 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enterprises", "0001_initial"),
        ("users", "0002_alter_user_date_birth"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="enterprise",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="enterprises.enterprise",
            ),
        ),
    ]
