# Generated by Django 5.1.3 on 2024-12-03 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productssales",
            options={
                "verbose_name": "Produto Vendido",
                "verbose_name_plural": "Produtos Vendidos",
            },
        ),
        migrations.AlterModelOptions(
            name="sales",
            options={"verbose_name": "Venda", "verbose_name_plural": "Vendas"},
        ),
        migrations.AlterField(
            model_name="sales",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
