# Generated by Django 5.1.3 on 2024-12-03 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "enterprises",
            "0002_alter_enterprise_options_alter_enterprise_address_and_more",
        ),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "Produto", "verbose_name_plural": "Produtos"},
        ),
        migrations.AlterModelOptions(
            name="productbrand",
            options={"verbose_name": "Marca do Produto"},
        ),
        migrations.AlterField(
            model_name="product",
            name="enterprise",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="enterprises.enterprise"
            ),
        ),
    ]
