# Generated by Django 5.1.2 on 2024-12-02 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0003_remove_user_enterprise_customuser'),
        ('sales', '0003_alter_sales_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
