# Generated by Django 5.1.2 on 2024-12-03 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("enterprise", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="enterprise",
        ),
        migrations.AlterModelOptions(
            name="enterprise",
            options={
                "verbose_name": "Empresa",
                "verbose_name_plural": "Empresas",
            },
        ),
    ]
