# Generated by Django 5.1.3 on 2024-12-03 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("addresses", "0002_alter_address_options_alter_city_options_and_more"),
        ("enterprises", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="enterprise",
            options={"verbose_name": "Empresa", "verbose_name_plural": "Empresas"},
        ),
        migrations.AlterField(
            model_name="enterprise",
            name="address",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="addresses.address"
            ),
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
