# Generated by Django 5.1.2 on 2024-11-29 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
        migrations.AlterModelOptions(
            name='productbrand',
            options={'verbose_name': 'Marca do Produto'},
        ),
    ]
